### ISSUE TITLE
 Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by FaragAnjumKureshi** [julianbrowne/graffeine#20]
S:\NTHU Assignments\Advanced DBMS\Final Project\graffeine-master\node_modules\socket.io\lib\store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                        ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (S:\NTHU Assignments\Advanced DBMS\Final Project\graffeine-master\node_modules\socket.io\lib\store.js:35:41)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (S:\NTHU Assignments\Advanced DBMS\Final Project\graffeine-master\node_modules\socket.io\lib\manager.js:16:13)
    at Module._compile (module.js:573:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! graffeine@0.0.5 start: `node server.js "graffeine"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the graffeine@0.0.5 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Farag\AppData\Roaming\npm-cache\_logs\2018-01-01T15_43_19_035Z-debug.log

**Comment by davidbenque** [comment]
+1 getting a similar error when trying to `node server`

```
MacBook-Pro-4:graffeine davidbenque$ node server
/Users/davidbenque/graffeine/node_modules/socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                         ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/Users/davidbenque/graffeine/node_modules/socket.io/lib/store.js:35:42)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/davidbenque/graffeine/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (module.js:635:30)
```

**Comment by ghost** [comment]
I get the same error
